### ISSUE TITLE
chromeapp:samples isn't working

### ISSUE THREAD

**Issue by jascination** [yeoman/generator-chrome-extension#100]
Hi,

I'm trying to install `chromeapp:samples`. When I do so, I'm asked "What samples would you like to use?"

The only two options are "libraries" and "samples". Choosing either results in this error:

```
undefined:14
    // client_id below is specifc to the application key. Follow the
    ^
SyntaxError: Unexpected token /
    at Object.parse (native)
    at module.exports.yeoman.generators.Base.extend.manifest (/Users/username/.nvm/v0.12.0/lib/node_modules/generator-chromeapp/samples/index.js:186:21)
    at /Users/username/.nvm/v0.12.0/lib/node_modules/generator-chromeapp/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

Using latest Node v0.12.0 and the latest version of yeoman.

**Comment by ragingwind** [comment]
This repo isn't for chromeapps.  Could you make a new issue to Chrome Apps? then I'll look

**Comment by ragingwind** [comment]
Fixed by https://github.com/yeoman/generator-chromeapp/commit/6bf1c697f05b60129ec3713567a70006cc451af5 @jascination thx
