### ISSUE TITLE
Drop CoffeeScript in favor of ES6 (Babel)

### ISSUE THREAD

**Issue by silvenon** [yeoman/generator-chrome-extension#109]
Ref. https://github.com/yeoman/generator-webapp/pull/543#issuecomment-111724489.

**Comment by arthurvr** [comment]
We already discussed this at https://github.com/yeoman/generator-chrome-extension/issues/106#issuecomment-111366074? Is there any reason to have this extra issue?

**Comment by silvenon** [comment]
Forgot to search, sorry.

**Comment by quiloos39** [comment]
Blurb.
