### ISSUE TITLE
Zip package cannot be installed into Chrome

### ISSUE THREAD

**Issue by kylehayes** [yeoman/generator-chrome-extension#113]
`Failed to load extension from: /Users/khayes/src/####-####-web/package/#### #### web-0.0.4.zip. Could not unzip extension for install.`

The message on the extensions page after shows :
`Failed to load extension from: ~/src/####-####-web/package/#### #### web-0.0.4.zip
Could not unzip extension for install.
Could not load manifest.`

If I unzip the archive myself and drag the folder into Chrome, it installs no problem.

**Comment by arthurvr** [comment]
What are you trying to do exactly? Installing the extension locally to develop it? If so I think you should just load the `app/` folder, not the zipped version.

**Comment by ragingwind** [comment]
How did you make a zip file. Use `gulp build` or not? I think you've zipped the `app` directory as root in zip file. manifest.json must be in root of zip file

**Comment by kylehayes** [comment]
I used the included `grunt build` command to package up the zip. For development, I use an unpacked extension. But to package it up, if you run grunt build, the workflow creates a zip file in the `package` directory. When I unzipped the archive, I can see that it is organized properly.

**Comment by ragingwind** [comment]
`Could not load manifest` error caused from so many reasons. Working well for development, I guess you have an issue of fields or values in manifest.json. May be crx or keys. I think it might not related to the generator.

**Comment by ragingwind** [comment]
I close the issue due to inactivity. Please feel free to open if you still have any issue

**Comment by techfoobar** [comment]
@kylehayes - If you remember, can you share how you finally fixed this issue?

**Comment by kylehayes** [comment]
Unfortunately I never did.
