### ISSUE TITLE
Add Gulp support

### ISSUE THREAD

**Issue by ragingwind** [yeoman/generator-chrome-extension#118]

**Comment by sindresorhus** [comment]
:+1: I would just replace Grunt with Gulp, but up to you.

**Comment by arthurvr** [comment]
Sure!

>  I would just replace Grunt with Gulp

Yeah, me too. I personally don't see much reasons people still want to use Grunt, the community seems to prefer Gulp these days, and having it as an option (such as the angular generator) is a maintainability risk.

**Comment by ragingwind** [comment]
I also prefer to gulp without an option and I think It would be more clear and simple to use the generator

**Comment by rscafi** [comment]
Since it's changed, can you guys tag it so that we can use it with npm?

**Comment by ragingwind** [comment]
I've testing with some issue. It will be release as soon as possible

**Comment by ISNIT0** [comment]
Hey guys, any idea when the Gulp version will be released?

**Comment by ragingwind** [comment]
Released  https://github.com/yeoman/generator-chrome-extension/releases/tag/
