### ISSUE TITLE
Move from Compass to Node Sass

### ISSUE THREAD

**Issue by Snugug** [yeoman/generator-chrome-extension#122]
Node Sass is more or less on par with Ruby Sass at this point. Compass support should be deprecated in favor of Node Sass, Autoprefixer, and maybe [Eyeglass](https://github.com/sass-eyeglass/eyeglass) if the plugin framework is wanted.

**Comment by arthurvr** [comment]
:+1:

**Comment by sindresorhus** [comment]
:+1:

**Comment by ragingwind** [comment]
Closed with new version v0.5.1
