### ISSUE TITLE
Add storage to permissions list

### ISSUE THREAD

**Issue by james2doyle** [yeoman/generator-chrome-extension#126]
I usually end up using the `storage` permission, especially when coupled with an options page.

Should this be added to the list of suggestions in the questions?

**Comment by ragingwind** [comment]
I'll add more permissions

**Comment by ragingwind** [comment]
Close https://github.com/yeoman/generator-chrome-extension/commit/e3a655c7b5f40a27bb887068fc5563a712e42787
