### ISSUE TITLE
Conflicting destination file names for useminPrepare task

### ISSUE THREAD

**Issue by nandwana92** [yeoman/generator-chrome-extension#131]
If I select options ui when generating, I get popup.html and options.html. useminPrepare attempts to write to the same destination file the script and styles in them, vendor.js and vendor.css. This breaks the grunt build task.

**Comment by ragingwind** [comment]
closed https://github.com/yeoman/generator-chrome-extension/commit/8688566d51924bffee105c8e92ca06443450fb19
