### ISSUE TITLE
Unable to start gulp build

### ISSUE THREAD

**Issue by selfrefactor** [yeoman/generator-chrome-extension#138]
I don't believe that it is any issue with the code, but rather than with the documentation. 
Can someone explain a bit more detailed how to start the gulp build process?
In the current documentation is just stated run "gulp build", but this doesn't work as there is no gulpfile created by Yeoman.

**Comment by sindresorhus** [comment]
The commit that switches grunt to gulp is not released yet. https://github.com/yeoman/generator-chrome-extension/commit/30b15c19a850c565e8a3a454beda6bfcb0ebb3cb

**Comment by selfrefactor** [comment]
Ok, that is fine, but still how I start the process when it is ready? From which directory I have to run the command?

**Comment by ragingwind** [comment]
@selfrefactor If you are not familiar with using yeoman see http://yeoman.io/learning/index.html

**Comment by boussouira** [comment]
If anyone else face this issue, this how i solve it after one hour of searching:

```
sudo npm install -g gulp
sudo npm install -g gulp-cli

npm install --save-dev babel-preset-es2015
npm install --save-dev babel-preset-react
npm install --save-dev babel-preset-stage-0
```

Edit `.babelrc` with:
```
{
  "presets": ["es2015", "stage-0", "react"]
}
```
