### ISSUE TITLE
Add webpack support for bundling modules for browser?

### ISSUE THREAD

**Issue by lobatt** [yeoman/generator-chrome-extension#144]
Hi,
Apology if this is a dumb question.
I tried to use this project to generate a chrome extension. but when I used require() in popup.js. the gulp build file didn't bundle my node modules to be used in browser.

Did I miss any configuration?
If this is not supported, I can figure out a way to integration webpack into curren gulp build file and submit a pull request.

**Comment by ragingwind** [comment]
@lobatt We have no plan to support and use webpack. But We always encourage you guys to make a new version of generator as a community generator. You can fork this repo or getting started with [yeoman generator APIs](http://yeoman.io/generator/)

**Comment by lobatt** [comment]
Ok, thanks! @ragingwind 

This might be too much to ask but what is the recommended solution to solve this problem with current generator?

not using require() in code?

**Comment by ragingwind** [comment]
I think that is out of issue for this repo and I have no idea about that. The question for using yeoman would be proper to [stackoverflow](http://stackoverflow.com/questions/tagged/yeoman) not here. You can find any of hints or create a post for.
