### ISSUE TITLE
.babelrc needed for using ES6 in gulpfile.babel.js

### ISSUE THREAD

**Issue by amrav** [yeoman/generator-chrome-extension#146]
Hi! I followed the instructions in the Readme to set up a new project, but `gulp babel` shows 

```
/Users/[...]/gulpfile.babel.js:2
import gulp from 'gulp';
^^^^^^

SyntaxError: Unexpected reserved word
```

The problem is fixed by adding a `.babelrc` file with

```
{
  "presets": ["es2015"]
}
```

and `gulp -v` gives me

```
[00:11:09] Requiring external module babel-register
[00:11:09] CLI version 3.9.1
[00:11:09] Local version 3.9.1
```

Is this supposed to happen, or am I doing something wrong?

**Comment by ragingwind** [comment]
You're right. It should be exist. Thanks,

**Comment by ragingwind** [comment]
Fixes https://github.com/yeoman/generator-chrome-extension/commit/81fdb65fa7c7bcd6bc3a8ac9b2998c16db012652
