### ISSUE TITLE
Creating and importing classes

### ISSUE THREAD

**Issue by mashhoodr** [yeoman/generator-chrome-extension#150]
Hey I was using this to create ES2015 classes in separate files but gulp gives me the following error when I do that:
'import' and 'export' may appear only with 'sourceType: module'

Its just a placeholder class:

app.js
```
export default class Something {

  constructor() {
    console.log('Hello World');
  }
}
```

contentscripts.js
```
import Something from './app.js'

new Something();
```

Both files are in the scripts.babel folder. Anything Im missing here?

**Comment by ragingwind** [comment]
Which generator version do you use? preset for presets is already supported.

**Comment by mashhoodr** [comment]
0.5.4

I can see the presets configured in my package.json, but its still giving me this error.

```
"babel-core": "^6.5.2",
"babel-preset-es2015": "^6.5.0",
```

Hints to what I can check will be appreciated.

Thanks.

**Comment by mashhoodr** [comment]
I think the issue is with linting not the babel configuration. I added the following bit to the eslint configuration under package.json the error stopped showing.

```
"parserOptions": {
      "ecmaVersion": 6,
      "sourceType": "module",
      "ecmaFeatures": {
        "modules": true
      }
    }
```

**Comment by mashhoodr** [comment]
Actually its because we need Browserify (duh), will create a PR for it.

**Comment by ragingwind** [comment]
@mashhoodr welcome.

**Comment by mashhoodr** [comment]
https://github.com/yeoman/generator-chrome-extension/pull/153

This is my first contribution to a chrome generator, feedback welcome!

**Comment by ragingwind** [comment]
I meant only for eslint not browserify. browserify should be optional.

**Comment by mashhoodr** [comment]
fixing the just eslint issue wont help, you need browserify for it to work. I can look into making the whole thing optional.

**Comment by ragingwind** [comment]
I'm not involved in this issue yet. I'll comment after looking for

**Comment by ragingwind** [comment]
I've understood it was related to a lint issue for module. the modules feature in ES2015 with content scripts on chrome extension is low priority so far as I think. I recommend to use put scripts into js array in manifest. But It is quite useful for some people who want to use modules. so I suggest that you can add new doc as a recipe like [webapp docs](https://github.com/yeoman/generator-webapp/tree/master/docs/recipes)

**Comment by mashhoodr** [comment]
alright, will look into this and update the PR as soon as I get the chance, thanks!

**Comment by mariosant** [comment]
Hey @mashhoodr, any luck with this one? I would love to use classes with my extension!

**Comment by ragingwind** [comment]
Close it now. reopen when you ready
