### ISSUE TITLE
"buildnumber" option of chromeManifest task is ignored

### ISSUE THREAD

**Issue by rsimoes** [yeoman/generator-chrome-extension#151]
When running `gulp build`, the `buildnumber` option appears to go unheeded. The version number in manifest.json is bumped even when `buildnumber` is set to false.

**Comment by ragingwind** [comment]
It's related to gulp-chrome-manifest. and It should be fixed with https://github.com/ragingwind/gulp-chrome-manifest/commit/82077ff00b486cdac1c5296cc39778150bbc4e39. which version of gulp-chrome-manifest do you use?

**Comment by rsimoes** [comment]
Roger, thanks. Sorry for the noise!
