### ISSUE TITLE
No gulpfile found when running gulp build

### ISSUE THREAD

**Issue by youssef06** [yeoman/generator-chrome-extension#154]
Hi, i followed these steps (from docs):

```
npm install --global yo gulp bower

npm install -g generator-chrome-extension

mkdir my-new-chrome-extension && cd $_

yo chrome-extension
```

However when i try running 'gulp babel' i get "No gulpfile found", i think i might be missing something...

### Update
Finally figured it out, i had to run 
`babel gulpfile.babel.js -o gulpfile.js`
Now it's working

**Comment by ragingwind** [comment]
Check your all of version and reinstall all of packages. I can't reproduce it
