### ISSUE TITLE
build task doesn't copy all of app's scripts/styles

### ISSUE THREAD

**Issue by paulirish** [yeoman/generator-chrome-extension#158]
I'm not sure this is your bug, but I'm super confused and think you probably can help.

Over here we've got an extension and its gulpfile: https://github.com/GoogleChrome/lighthouse/blob/c175157f194c27d85fef67f7b930b996859c26b9/extension/gulpfile.babel.js

when I run `gulp build` it copies some files into dist but not everything in app. And it seems like the "chromeManifest" task is moving those pieces, which is a little confusing

**Comment by paulirish** [comment]
Fixed the issue here: https://github.com/GoogleChrome/lighthouse/pull/44

I think the root fix is being more clear in the tasks about what copies to dist.

**Comment by ragingwind** [comment]
the reason there is no block expression in popup.html for useref, which is default function to move and copy style/js into dist in the generator. You can use own copy task instead, if or not? please see [this popup.html](https://github.com/yeoman/generator-chrome-extension/blob/master/app/templates/popup.html#L9) and patch your gulpfile with this patch https://github.com/yeoman/generator-chrome-extension/commit/d2167c1f82d8729f8d2078ed0abb5fecf5c3e536

**Comment by paulirish** [comment]
whoa. I definitely didn't have a copy task in the gulpfile at all. 

it was @samccone who initially created it, perhaps he used an old version or went a little crazy with the delete key


thanks for taking a look, @ragingwind and apologies for the super vague report!

**Comment by paulirish** [comment]
lol i am dumb.

you PRd lighthouse. i thought it was a PR for this generator. :)

yeah that all makes sense now. :)

**Comment by ragingwind** [comment]
@paulirish no problem. I'm so glad it is helpful

**Comment by samccone** [comment]
Hmm yeah I did not choose the pop-up scaffold that is prob why 😐😌😮🤓

**Comment by ragingwind** [comment]
@samccone probably :)
