### ISSUE TITLE
Manifest version does not update

### ISSUE THREAD

**Issue by oddui** [yeoman/generator-chrome-extension#159]
The `chromeManifest` task does not seem to update builder number for me. I can reproduce by generating using 0.5.6 and run `gulp chromeManifest`.

**Comment by ragingwind** [comment]
It only affects on generated manifest.json under `dist`. Did you mean that origin manifest.json under `app`? If you would like to update the version in manifest every build time, you should add some of codes for it

**Comment by oddui** [comment]
@ragingwind that makes sense, thanks for clarification.

**Comment by iamchriswick** [comment]
Any thought on best way to achieve this by adding functions to gulpfile.babel.js?

**Comment by ragingwind** [comment]
@iamchriswick Do you want to make build number in `app/manifest.json` to update by you running `gulp chromeManifest or gulp` command every time?
