### ISSUE TITLE
gulp build does not create a zip file

### ISSUE THREAD

**Issue by gauravarora** [yeoman/generator-chrome-extension#164]
From the documentation it looks like `gulp build` should create a zip file but it does not. Did I misunderstand the docs?

**Comment by oddui** [comment]
`gulp package` will do. But I agree the doc is a bit confusing...

**Comment by ragingwind** [comment]
Guys. sorry for confusing. It's not updated yet. `package` task was in `build` task at previous version. I will update it as soon. Thanks for reporting

**Comment by gauravarora** [comment]
How do I go about updating a project I already generated to use ```package```?
