### ISSUE TITLE
Improvement: Use webpack to bundle the top-level scripts 

### ISSUE THREAD

**Issue by darthtrevino** [yeoman/generator-chrome-extension#170]
I recently used the generator to bootstrap up a chrome extension plugin, and I ended up using webpack to bundle the root scripts. This ends up simplifying build a bit:
* `scripts.babel` doesn't need to transpile over to `scripts`. It can bundle into the `dist` dir. This means that no transient stuff needs to exist in `app/`.
* linting can be performed in the webpack asset pipeline using the `eslint-loader`.
* Wiredep can be removed (unless you want to keep it around to auto-include CSS).

**Comment by ragingwind** [comment]
Yes, I understand that webpack has a lot of benefits when it comes to bundling. However, I expect that migrate to use webpack cause some of conflicts among the current user. So I recommend that make a new version of generator for chrome extension using webpack. It would be great and I'm pleased very much to use it. Or Writing receipts also great solution for this https://github.com/yeoman/generator-webapp/tree/master/docs/recipes

**Comment by ragingwind** [comment]
Close it now
