### ISSUE TITLE
Test framework installation does not direct to the correct bower directory

### ISSUE THREAD

**Issue by matchai** [yeoman/generator-chrome-extension#173]
Upon scaffolding a fresh project, launching the mocha index.html in Google Chrome resolves to a plain white screen. Upon investigating, it appears to be looking for assets in `../bower_components/mocha`, which would mean that the bower_components directory is in the root of the project folder.

The .bowerrc file sets the bower directory to `app/bower_components`.

The issue is solved locally by changing all mention of `../bower_components/mocha` with `../app/bower_components/mocha`.

This issue also occurs with the installation of Chai and after looking at the Jasmine generator, is likely to occur for it as well.

**Comment by ragingwind** [comment]
To develop an extention on the `app` as a root of program, `bower_components` shoud be under the `app`. I think that test files also put into the `app`

**Comment by ragingwind** [comment]
Closing it now
