### ISSUE TITLE
add 'wiredep' to watch and build run sequence

### ISSUE THREAD

**Issue by BjornMelgaard** [yeoman/generator-chrome-extension#175]
I can't understand, why html task (compile to 'dir') [run before watch task](https://github.com/yeoman/generator-chrome-extension/blob/master/app/templates/gulpfile.babel.js#L103), if in testing we add to chrome 'app' directory, wiser will be replace it with wiredep task

**Comment by ragingwind** [comment]
We don't need to use it. It will be removed

**Comment by ragingwind** [comment]
https://github.com/yeoman/generator-chrome-extension/commit/c70a1d7b1b733f8b653ccf84c92f764f38307e96

**Comment by BjornMelgaard** [comment]
I add wiredep to build and the beginning of watch task as well
```
gulp.task('watch',  ['lint', 'babel', 'wiredep'],() => {
  $.livereload.listen();

  gulp.watch([
    'app/*.html',
    'app/scripts/**/*.js',
    'app/images/**/*',
    'app/styles/**/*',
    'app/_locales/**/*.json'
  ]).on('change', $.livereload.reload);

  gulp.watch('app/scripts.babel/**/*.js', ['lint', 'babel']);
  gulp.watch('bower.json', ['wiredep']);
});

gulp.task('build', (cb) => {
  runSequence(
    'lint', 'babel', 'chromeManifest',
    ['wiredep', 'html', 'images', 'extras'],
    'size', cb);
});
```
