### ISSUE TITLE
Deletes content script when you use 'gulp build'

### ISSUE THREAD

**Issue by emarkchrome** [yeoman/generator-chrome-extension#179]
For some reason, the gulp watch process terminated with an error. When I rebooted it to continue working, it deleted my entire application(Which is in a content script). I won't be using this even if it is fixed, but please fix it. I don't know much about gulp, so I don't have anything useful to add to the matter. If I'm using it wrong, please tell me.

**Comment by ragingwind** [comment]
First of all, I don't know why your entire app has been deleted after crash from gulp watch task. We just use gulp api for post-processing like reload or do babel. You should ask it to gulpjs or give me more details and hints

**Comment by emarkchrome** [comment]
I know and I'm sorry I can't give more. When I went back into the content
script, it had reset to what the generator had scaffolded.

**Comment by ragingwind** [comment]
I think you are confused to use es2015 with babel. If you were generating an extension without [no-babel](https://github.com/yeoman/generator-chrome-extension#options). It result in watch/build  always generate compiled source into `script` path. It means that you should write your code at scripts in `app/scripts.babel/*.js`. And I couldn't get any idea except above I mentioned. 

I will close it now but you can always open when you got any clue
