### ISSUE TITLE
How I can use chrome.tabs.executeScript?

### ISSUE THREAD

**Issue by Igor-Maf** [yeoman/generator-chrome-extension#190]
Hi. How I can use `chrome.tabs.executeScript` from my _background.js_? The `gulp build` is watching only in background scripts and scripts, whitch were loaded from .html files. `gulp-chrome-manifest` also don`t see the scripts if I want to add them to `web_accessible_resources`. Its a very important features for us.

**Comment by ragingwind** [comment]
Please look for api docs about how to use apis
