### ISSUE TITLE
manifest.json config faild

### ISSUE THREAD

**Issue by chrisred8** [yeoman/generator-chrome-extension#199]
hi.
i from try 'http://yeoman.io' build base project 

but i from chrome load app, can't load app

so `manifest.json` file line 12~15

```json
"scripts": [
      "scripts/chromereload.js",
      "scripts/background.js"
    ]
```

i try modify
```json

"scripts": [
      "scripts.babel/chromereload.js",
      "scripts.babel/background.js"
    ]

```

it is ok load , thinks

**Comment by ragingwind** [comment]
run `gulp babel` before load to chrome https://github.com/yeoman/generator-chrome-extension#babel

**Comment by mischah** [comment]
@chrisred8 Feel free to come back over here if you still encounter problems.
