### ISSUE TITLE
grunt test -> "Warning: PhantomJS timed out, possibly due to a missing Mocha run() call."

### ISSUE THREAD

**Issue by skeate** [yeoman/generator-chrome-extension#43]
Using: 
generator-chrome-extension v0.2.5
node v0.10.26
Windows 7 64-bit

On a freshly generated project, running `grunt test` results in 

```
Testing: http://localhost:9000/index.html


Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --
force to continue.

Aborted due to warnings.
```

after a few seconds. However, if I pull up the URL it's accessing (after the connect task starts up the server, before that message appears), I see that Mocha has run the test just fine.

Also possibly noteworthy: if I deliberately make the test fail (adding in a throw;), then the task completes, with:

```
Testing: http://localhost:9000/index.html


  0 tests complete (0 ms)

>> 0 passed! (0.00s)

Done, without errors.
```

**Comment by brendonco** [comment]
i'm getting PhantomJS timed out. I'm using "grunt-mocha": "^0.4.12", and grunt

**Comment by izhan** [comment]
+1 thanks @briangershon!

**Comment by suifengfengye** [comment]
+1 thanks @briangershon. but I run `bower install mocha` .
