### ISSUE TITLE
"grunt build" fails for an extension without any CSS files

### ISSUE THREAD

**Issue by aawc** [yeoman/generator-chrome-extension#52]
I created an extension with no UI action and no extra UI features because my extension just runs in the background and acts on outgoing webRequests.

Without making any changes, I then proceeded to `grunt build` the skeleton extension and got the error:

`Execution Time (2014-04-20 01:46:31 UTC)`
`imagemin:dist  1.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%`
`Total 1.4s`
`>> No "cssmin" targets found.`
`Warning: Task "cssmin" failed. Use --force to continue.`

**Comment by sergiyvoytovych** [comment]
you need add comments for build css files in your app like this
`
    
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">



    <link rel="stylesheet" href="styles/styles.css">
`
