### ISSUE TITLE
Remove key element from manifest when compressing

### ISSUE THREAD

**Issue by frapontillo** [yeoman/generator-chrome-extension#59]
The `chrome.identity`(https://developer.chrome.com/apps/identity) API needs the `key` element to exist in the manifest during debugging as well as in release. Since the `key` is automatically added by the WebStore, it won't accept any package that have it already set.

My proposal is to edit the Gruntfile so that it takes care of deleting the `key` element from the manifest right before `compress`ing, without touching the original `manifest.json` used while debugging.

**Comment by nikhilknoldus** [comment]
@ragingwind You must not close this issue, this is a very legit issue, I am also facing the same. and the manifest.json guidelines itself says that "key" is valid property there, but as @frapontillo saying when I upload my zip folder it is yelling at me.

**Comment by SJcoded** [comment]
I agree, I'm in the same boat and this thread seems like it might help solve it

**Comment by surfapps** [comment]
> @ragingwind You must not close this issue, this is a very legit issue, I am also facing the same. and the manifest.json guidelines itself says that "key" is valid property there, but as @frapontillo saying when I upload my zip folder it is yelling at me.

Have you found a solution?
