### ISSUE TITLE
JSHint errors right off the bat

### ISSUE THREAD

**Issue by seriema** [yeoman/generator-chrome-extension#76]
I just installed the generator and scaffolded a project. Ran `grunt` and was greeted with this:

```
Running "jshint:all" (jshint) task

test/spec/test.js
  line 11  col 9  Expected '}' to have an indentation at 11 instead at 9.
  line 12  col 5  Expected '}' to have an indentation at 7 instead at 5.
  line 13  col 1  Expected '}' to have an indentation at 3 instead at 1.

✖ 3 problems

Warning: Task "jshint:all" failed. Use --force to continue.

Aborted due to warnings.
```

Sad panda. Panda likes things to work out of the box.

Config chosen: no extra options (no UI Actions or UI Features)

**Comment by Kageetai** [comment]
Well, I just stumbled upon the exact same problem, but updating the `generator-mocha` to 2.0 didn't help and also using jasmine neither. How did you solve the problem?
