### ISSUE TITLE
Where to place vendor dependencies for concatenation during build?

### ISSUE THREAD

**Issue by ghost** [yeoman/generator-chrome-extension#82]
Where in the generated skeleton directory structure do we place vendor dependencies (like jQuery, lodash, etc.) that we'd like to be concatenated in one JS during build task? 

I can see placeholders like `<!-- build:js scripts/vendor.js -->` in generated HTML files, but where to put vendor source files? I tried placing in `app/scripts/vendor` but when invoking `build` the generated vendor.js is empty. Maybe elaborate a bit in README.md?

**Comment by axsuul** [comment]
After going through those two resources it is still a bit unclear to me on how to populate `vendor.js`. Right now I simply include bower packages directly, i.e. 

```html
<link href="bower_components/foundation/css/foundation.css" rel="stylesheet">
```

Any suggestions?

**Comment by ragingwind** [comment]
@aponxi You can do that it's not problem. `vendor.js` that isn't mandatory for every case. It's a one of good practice. the most of cases, vendor.js has a common library kill jquery that can be included multiple times. on the other scripts, it consist of user scripts.

**Comment by stupid-genius** [comment]
That does not--at all--answer the question.  I've added scripts to the vendor.js block as shown in both the links you posted and vendor.js is still empty, as is the copy under .tmp/concat.

So, the question remains: where do you place vendor scripts for them to be picked up by the build?

**Comment by ragingwind** [comment]
@stupid-genius It was not helpful to you? https://github.com/yeoman/grunt-usemin#transformation-flow

**Comment by stupid-genius** [comment]
I responded because your answer provided an alternative (one that happened to work for the OP), but did not answer the original question.  I deleted my response because immediately after I posted it, I found a SO post that reminded me that I needed to run `grunt bowerInstall` manually.
