### ISSUE TITLE
Support inforbars

### ISSUE THREAD

**Issue by ragingwind** [yeoman/generator-chrome-extension#92]
https://developer.chrome.com/extensions/infobars

**Comment by smurfpandey** [comment]
This API is still experimental and only in dev channel. Will it be good to add it now? Do you think we should wait for it to come in stable?

**Comment by sindresorhus** [comment]
Wait until it's stable.

**Comment by ragingwind** [comment]
@smurfpandey Just make a issue to remember.

**Comment by smurfpandey** [comment]
:+1:

**Comment by simonoff** [comment]
The chrome.infobars API is no longer supported. We recommend using a Page Action instead.

**Comment by ragingwind** [comment]
@simonoff Thanks for update. I close the issue
