### ISSUE TITLE
Gulp support

### ISSUE THREAD

**Issue by chester1000** [yeoman/generator-chrome-extension#96]
I'm rewriting build system to Gulp for my extensions. If you think it makes sense I can PR it here once I'm done. I'm asking because, adding it will probably add a lot of maintenance work with every further change.

**Comment by ragingwind** [comment]
Thanks bug this generator keep using Grunt. We would make a new repository for new generator If we need that. like generator-gulp-webapp

**Comment by ragingwind** [comment]
You can also make a new generator for extension with gulp. We love it.

**Comment by chester1000** [comment]
I'll think about it. Thanks!

**Comment by kmb32123** [comment]
@chester1000 Did you ever end up going through with this?

**Comment by chester1000** [comment]
@kmb32123 nope, I don't think I ever finished it.
