### ISSUE TITLE
bower components not included in packaged archive file?

### ISSUE THREAD

**Issue by vohof** [yeoman/generator-chrome-extension#99]
I'm using the bower components from a background script.

```
    "background": {
        "scripts": [
            "bower_components/jquery/dist/jquery.min.js",
            "scripts/chromereload.js",
            "scripts/background.js"
        ]
    }
```

**Comment by ragingwind** [comment]
First of all. check your bower path one more. and then, If there is no problem? Could you post your build log like that is mine. i didn't face the problem.

Configuration is now:
```
  concat:
  { background:
   { src:
      [ 'app/bower_components/jquery/dist/jquery.min.js',
        'app/scripts/background.js' ],
     dest: 'dist/scripts/background.js' } }
```

**Comment by vohof** [comment]
Oh, that's my manifest file.

**Comment by vohof** [comment]
I'm sorry, I should have just checked the generated files first. They indeed got concatenated. It was named `background.js` just the same so I immediately arrived to wrong assumptions.
